openapi: "3.1.0"
info:
  description: a customer relation manager for a kayak rental shop
  title: Customer Relation Manager API
  version: 1.0.0
paths:
  /api/customers:
    post:
      description: Register a new customer. Newly registered customers will be assigned an ID, registration date and an expiration date..
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Customer successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                    example: successfully registered John Smith as a new customer
        '400':
          description: Bad Request
          content:
            application/json:
              examples:
                unknown field:
                  value:
                    error:
                      favourite_colour: [Unknown field.]
                unspecified content type:
                  value:
                    error: The request payload is not in JSON format
                missing required parameter:
                  value:
                    error:
                      first_name: [Missing data for required field.]
                      last_name: [Missing data for required field.]
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              example:
                error: The request payload is not in JSON format
components:
  schemas:
    Customer:
      type: object
      properties:
        first_name:
          type: string
          format: null
        last_name:
          type: string
        email:
          type: string
          format: email
        phone_number:
          type: string
        address:
          type: string
        city:
          type: string
        province:
          type: string
      required:
        - first_name
        - last_name
      example:
        first_name: John
        last_name: Smith
        email: user@example.com
        phone_number: '+1 604-296-1234 '
        address: 1234 Main st
        city: Vancouver
        province: British Columbia
